### ISSUE TITLE
Update the circuit

### ISSUE THREAD

**Issue by umutsevdi** [umutsevdi/wear-pico#2]
Create a section in the [wiki](https://github.com/umutsevdi/wear-pico/wiki) which guides new comers to build the hardware correctly.

**Issue**:
The circuit has been updated since the paper was released.

**Comment by KozhaAkhmet** [comment]
* Added a reference to the README.md.
* Added updated board and connections to the [Hardware Overview](https://github.com/umutsevdi/wear-pico/wiki/1-Hardware-Overview) section of the wiki page.
