### ISSUE TITLE
Lack of Error Handling in I2C Communication in dev.c

### ISSUE THREAD

**Issue by MakaremHind** [umutsevdi/wear-pico#5]
# Lack of Error Handling in I2C Communication in `dev.c`

## Description
The dev.c file currently lacks proper error handling for `I2C` communication in the `DEV_I2C_Read_Byte()` function. Specifically, the function does not check the return value to verify if the communication was successful. This oversight can lead to undefined behavior or incorrect data processing if an `I2C` read operation fails, as the system could operate on invalid or corrupted data.

## Symptoms
If the `I2C` communication fails, the lack of error handling may lead to:
* Unpredictable Behavior: The system may perform operations based on erroneous or corrupted data, leading to incorrect functionality.
* Data Integrity Issues: Any processes dependent on I2C data may operate with invalid inputs, leading to potential data corruption.
* System Instability: Critical functions may become unstable if they rely on I2C communication, which may lead to unsafe or unintended behaviors.

## Cause
The issue occurs because the function `DEV_I2C_Read_Byte()` does not check the return status after attempting to read from the I2C bus. Without checking for errors, the program assumes the read operation was successful and proceeds, which may not be the case if the communication fails.

## Suggested Solution
To resolve this issue, it’s recommended to:
* Add Error Handling: Check the return value of the `DEV_I2C_Read_Byte()` function after each `I2C read operation`.
* Implement Retry Logic (optional): In case of transient failures, implement a retry mechanism to attempt the read operation multiple times before failing.
* Gracefully Handle Errors: If the I2C communication fails after retries, handle the failure gracefully by logging an error, triggering a fallback mechanism, or stopping dependent processes.

## Example Fix
Here is a potential solution that checks the return value of `DEV_I2C_Read_Byte()` and includes basic error handling:

```c
uint8_t data;
int result = DEV_I2C_Read_Byte(address, &data);

if (result != 0) {  // Assuming non-zero indicates an error
    printf("Error: Failed to read from I2C device at address 0x%02X\n", address);
    // Optionally, implement retry logic here or handle the error as needed
    return -1;  // Return an error code to indicate failure
}

// Proceed with processing the valid data
```
### `In this example:`
* Error Checking: We check if the return value of `DEV_I2C_Read_Byte()` indicates an error.
* Logging: An `error message` is printed if the `I2C` read fails.
* Graceful Failure: The function returns an error code to indicate that the read operation failed.

## Verification Steps
To verify that this fix works as expected:
* Simulate I2C Communication Failure: Test the code under conditions where the I2C communication fails (e.g., disconnect the I2C device or use an invalid address).
* Verify Error Handling: Confirm that the error is detected, logged, and handled without causing further issues in the system.
* Test Successful Read Operations: Ensure that the error handling does not interfere with successful I2C reads and that normal functionality is preserved.

## Conclusion
Implementing this `error handling for I2C communication` is critical to ensure `system stability` and `data integrity`. Without it, the system is vulnerable to unpredictable behavior, especially if I2C communication fails during operation. Proper error handling will make the system more robust, reliable, and easier to troubleshoot in the event of communication issues.

**Comment by umutsevdi** [comment]
Can you provide the exact line where `DEV_I2C_Read_Byte` causes an issue?
```bash
$ for i in `find -type f -not -path "./waveshare/*"` ;
    do grep DEV_I2C_Read_Byte $i && echo $i;
done

XY.Gesture = DEV_I2C_Read_Byte(address, 0x01);
./wp_apps/src/display.c
```

As seen above, It is only used in `/wp_apps/src/display.c` under a callback function. It calls the `gpio_get` on Pico implementation which returns `false` if there is no data. So there is no need for error handling.

**Comment by MakaremHind** [comment]
Thank you for clarifying the usage of `DEV_I2C_Read_Byte()` in `display.c`.

I see that `DEV_I2C_Read_Byte()` is used here:

```c
XY.Gesture = DEV_I2C_Read_Byte(address, 0x01);
```
It’s called within a callback function, relying on `gpio_get` for implicit error handling. While this works in this context, adding explicit error handling within `DEV_I2C_Read_Byte()` could make the function more resilient and not dependent solely on `gpio_get`, especially if used outside this callback or if the I2C behavior changes.

Moreover, Consistent error handling could prevent subtle bugs if this function is used elsewhere or if additional data processing is added later. Logging errors directly in `DEV_I2C_Read_Byte()` would provide immediate feedback on I2C failures, which is helpful for diagnosing intermittent issues.

**Comment by umutsevdi** [comment]
XY.Gesture has multiple states. It can enable gestures or not. If the received signal is 1 that means the mode should be set. If 0 it shouldn't. 
Even Waveshare developers provide same part of code for checking the callback. The following code is from Waveshare's official example:

```c
void Touch_INT_callback(uint gpio, uint32_t events)
{
    if (XY.mode == 0)
    {
        XY.Gesture = DEV_I2C_Read_Byte(address,0x01);
        flag = TOUCH_IRQ;
    }
    else
    {
        flag = TOUCH_IRQ;
        XY = Touch_1IN28_Get_Point();  
    }
}

```
